services:
  web:
    build: .
    ports:
      - "5001:5000"  # Maps host port 5001 to container port 5000
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URL: postgresql://admin:admin_password@db:5432/school_db
      SECRET_KEY: my_super_secret_key
    depends_on:
      - db
      - redis
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
      - migrations_data:/app/migrations

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: my_redis_password  # Set Redis password here
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  migrations_data:
  redis_data: